### ISSUE TITLE
Replace Zoo-related icons & logos

### ISSUE THREAD

**Issue by tammets** [centre-for-educational-technology/rada2#1]

**Comment by pjotrsavitski** [comment]
We might also get rid of Zoo related roles, options and everything else that is related to those. This will also include initial geolocation that should most probably be preset within a config with capability of overriding it using environment variables.

This assumes that we are not expecting additional contexts like zoos/organisations to be present. It is not of utmost importance, but getting rid of unneeded code should be beneficial in the long run.

**Comment by pjotrsavitski** [comment]
I'd say that it should be done. Maybe there are some texts here and there, but those would just have to be fixed as we go.
