### ISSUE TITLE
Users are able to see previous answers for Public Path games

### ISSUE THREAD

**Issue by tammets** [centre-for-educational-technology/rada2#15]
![Screenshot 2021-04-15 at 10 51 38](https://user-images.githubusercontent.com/380007/114833880-b334a280-9dd8-11eb-8868-9e60cfa42ec9.png)

Use dialog for previous answers (newest answers first):

![Screenshot 2021-04-15 at 10 53 06](https://user-images.githubusercontent.com/380007/114834098-e840f500-9dd8-11eb-984e-a2e7483f3d69.png)

**Comment by pjotrsavitski** [comment]
Should be almost done. Will need to check the query and make sure it can't be optimised and all the conditions and order by clauses are using indexed columns. Checking how previous results dialog behaves within a game would also be useful to make sure that change in component signature did not break anything.
