### ISSUE TITLE
Update footer text

### ISSUE THREAD

**Issue by tammets** [centre-for-educational-technology/rada2#16]
**Old:**

Minimum requirements: operating system iOS (version 10) or Android 7. At least 3G internet connection and working GPS module is needed.

**New:**

Minimum requirements: operating system iOS (version 14) or Android 8.1. At least 4G internet connection and working GPS module is needed.

**Comment by pjotrsavitski** [comment]
Changed Androind version to 8.1 as it seems to be the oldest supported one. Wikipedia also mentioned iOS 12.5 still being supported.

I'd still guess that most if not all of the code would still work on older versions :)
