### ISSUE TITLE
User registration - e-mail validation error/bug

### ISSUE THREAD

**Issue by tammets** [centre-for-educational-technology/rada2#17]
While creating a new user, form displays message about existing address even if it is not already existing:

![Screenshot 2021-04-15 at 12 25 22](https://user-images.githubusercontent.com/380007/114995231-47207000-9ea6-11eb-8781-91df826e8309.png)

**Comment by pjotrsavitski** [comment]
Could not reproduce.

That kind of visual will be displayed if someone tries to register with an email address that has already been taken and then changes it to something else. Validation is done on the server side and visuals will not be removed on changes being made to the input.
