### ISSUE TITLE
Users are able to see given answers to task by other users 

### ISSUE THREAD

**Issue by tammets** [centre-for-educational-technology/rada2#2]
Answers are visible before submitting your own answer.

![Screenshot 2021-02-16 at 11 57 51](https://user-images.githubusercontent.com/380007/108047257-427a3f80-704e-11eb-9894-6fe2bc1a0376.png)

![Screenshot 2021-02-16 at 13 33 19](https://user-images.githubusercontent.com/380007/108057627-8b84c080-705b-11eb-8dff-e196381f2789.png)

**Comment by pjotrsavitski** [comment]
Would that apply to all question types or only affect some of those?

Example: once correct answer or multiple correct answers have correct and incorrect answers and user can not really add answers that differ from all the others.

**Comment by tammets** [comment]
It applies for photo and freeform answer type of questions / tasks.

**Comment by pjotrsavitski** [comment]
This is related to #4

**Comment by pjotrsavitski** [comment]
The endpoint will not respond with data if Task is not marked as Public Path or has been marked as inactive.
