### ISSUE TITLE
Users are able to add photos from selected registries

### ISSUE THREAD

**Issue by tammets** [centre-for-educational-technology/rada2#3]
https://register.muinas.ee
https://ajapaik.ee/?page=1

![2021-03-12 11 23 39](https://user-images.githubusercontent.com/380007/110919947-797a0300-8325-11eb-9666-fc900e6f0ac1.gif)

**Comment by pjotrsavitski** [comment]
This is working as expected, with only a few smaller issues still remaining:
* table-like view of images having empty spaces for rows with different image height
* image upload will remove an existing image even if fetching an external one will fail
* using images from external sources can possibly throw exception and those would need to be handled, with some messages being shown
