### ISSUE TITLE
Add new game type - public path

### ISSUE THREAD

**Issue by tammets** [centre-for-educational-technology/rada2#4]
By checking appropriate checkbox, all results (submitted answers) will be public during and after the gameplay:

![Screenshot 2021-03-30 at 10 36 04](https://user-images.githubusercontent.com/380007/112951277-d9edaa80-9143-11eb-8864-6c848e43cb32.png)

**TODO**: Add views for:

- Listings
- Single Game

**Comment by pjotrsavitski** [comment]
Should those also have some special kind of icon somewhere and listed separately?
