### ISSUE TITLE
Users are able to use previously published tasks (Activity items)

### ISSUE THREAD

**Issue by tammets** [centre-for-educational-technology/rada2#5]
![Screenshot 2021-02-16 at 11 41 30](https://user-images.githubusercontent.com/380007/108045275-f5956980-704b-11eb-89d0-035ec03c6002.png)

**Comment by pjotrsavitski** [comment]
I'm not sure that tasks have any kind of status, though we should be able to allow using already existing tasks.

I think that we should be using button groups in all the cases where multiple button are placed next to each other.

**Comment by tammets** [comment]
> I'm not sure that tasks have any kind of status, though we should be able to allow using already existing tasks.
> 
> I think that we should be using button groups in all the cases where multiple button are placed next to each other.

I agree.

**Comment by pjotrsavitski** [comment]
Should be working as expected.
