### ISSUE TITLE
Users are able add tasks without creating a new Game

### ISSUE THREAD

**Issue by tammets** [centre-for-educational-technology/rada2#6]
![Screenshot 2021-02-16 at 11 38 26](https://user-images.githubusercontent.com/380007/108044916-84ee4d00-704b-11eb-8e6b-a2dc34c19216.png)

**Comment by pjotrsavitski** [comment]
This should include bringing back the listing view for tasks as is shown in the picture? maybe it would be useful to also show counts for games and tasks somewhere? The data could be cached and cache could be reset each time game or task is being crated/updated/removed.

**Comment by tammets** [comment]
> This should include bringing back the listing view for tasks as is shown in the picture? maybe it would be useful to also show counts for games and tasks somewhere? The data could be cached and cache could be reset each time game or task is being crated/updated/removed.

Yes, bring back the listing. Counts for tasks and games could be displayed after listing title (All Tasks).

**Comment by pjotrsavitski** [comment]
Showing counts will be handled in different issues.
